sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: I88dZVVl5CgX0dVQZhQ2w+3WEsptiDwYASbJcY3DxHC4eHYkQLKUsZA3Kmya5zeKOr+70PkD3afEgPH1Yd7/sUx2+4lpgseEPdVw4uFYjVfRWbeM+ZtrRo+I/ghzF6Hd3LMZzwR1Z1O4cv7FGx8NB6Y3c4oudrgpBf1h3LS9ns+/LYehMWIoBnUtt4FSsQ7+UpWOOV2rqVo+PzAjjnYfq36hnz7Cn6DLp/W9dEznHNSjKy1jqUsZMZ7Uybyy73tDLqTROttZtCBSBm5+qAsEWjT324KKQ1BSN5BamTOoYSSZP2PEvdfg6+3xhTTF3iPG0XGGfzju2h5c0p8JrBa/eBfF56juVs/NdqphjikQQ7sZDqEIqRXUpQU8BbkRbcNtS8aqhWll4333knpUCpaFPdfALpzqm6FcRSWjGKCEkKqJDnIei6G5q42QBfE2QtREnO6PWOU5Eu1yDRaodIxg4GuaZu82HKwNTkEnSNKn1lGO2Iv2lnUE3K57NEB8K40fEsyUtbK9fWb0vB8i89s3dZj4W3GCf+DNWCXFfCSOznLAm6BCWUiqJYA1h1lVsShiJ+3jh8TbQOOgTpvVm3YgT1Ami7F7h22v2TbsWyyQJxp8R/uu65nL4vnoDQnbGdtDbb9orC+8dKiqNvDtZmdGFeUsl5PqjXIR1/c6OckomD0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Inside-of-the-Cup---Volume-08_5363
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy